#ifndef PREC
#error "PREC not defined"
#endif

PREC(NONE,		NONE)
PREC(BINDING,	NONE)
PREC(SEMI,		RIGHT)
PREC(IF,		NONE)
PREC(COMMA,		NONE)
PREC(OR,		RIGHT)
PREC(AND,		RIGHT)
PREC(COMPARE,	LEFT)
PREC(CONCAT,	RIGHT)
PREC(TERM,		LEFT)
PREC(FACTOR,	LEFT)
PREC(POWER,		RIGHT)
PREC(UNARY,		NONE)
PREC(APP,		LEFT)
PREC(ACCESS,	NONE)
PREC(PREFIX,	NONE)
